/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PaymentGatewayService } from "../paymentGateway.service";
import { PaymentGatewayCreateInput } from "./PaymentGatewayCreateInput";
import { PaymentGateway } from "./PaymentGateway";
import { PaymentGatewayFindManyArgs } from "./PaymentGatewayFindManyArgs";
import { PaymentGatewayWhereUniqueInput } from "./PaymentGatewayWhereUniqueInput";
import { PaymentGatewayUpdateInput } from "./PaymentGatewayUpdateInput";

export class PaymentGatewayControllerBase {
  constructor(protected readonly service: PaymentGatewayService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentGateway })
  async createPaymentGateway(
    @common.Body() data: PaymentGatewayCreateInput
  ): Promise<PaymentGateway> {
    return await this.service.createPaymentGateway({
      data: data,
      select: {
        createdAt: true,
        createdBy: true,
        credentials: true,
        enabled: true,
        gatewayName: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentGateway] })
  @ApiNestedQuery(PaymentGatewayFindManyArgs)
  async paymentGateways(
    @common.Req() request: Request
  ): Promise<PaymentGateway[]> {
    const args = plainToClass(PaymentGatewayFindManyArgs, request.query);
    return this.service.paymentGateways({
      ...args,
      select: {
        createdAt: true,
        createdBy: true,
        credentials: true,
        enabled: true,
        gatewayName: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentGateway })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async paymentGateway(
    @common.Param() params: PaymentGatewayWhereUniqueInput
  ): Promise<PaymentGateway | null> {
    const result = await this.service.paymentGateway({
      where: params,
      select: {
        createdAt: true,
        createdBy: true,
        credentials: true,
        enabled: true,
        gatewayName: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentGateway })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePaymentGateway(
    @common.Param() params: PaymentGatewayWhereUniqueInput,
    @common.Body() data: PaymentGatewayUpdateInput
  ): Promise<PaymentGateway | null> {
    try {
      return await this.service.updatePaymentGateway({
        where: params,
        data: data,
        select: {
          createdAt: true,
          createdBy: true,
          credentials: true,
          enabled: true,
          gatewayName: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentGateway })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePaymentGateway(
    @common.Param() params: PaymentGatewayWhereUniqueInput
  ): Promise<PaymentGateway | null> {
    try {
      return await this.service.deletePaymentGateway({
        where: params,
        select: {
          createdAt: true,
          createdBy: true,
          credentials: true,
          enabled: true,
          gatewayName: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
