/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Communication as PrismaCommunication } from "@prisma/client";

export class CommunicationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CommunicationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.communication.count(args);
  }

  async communications(
    args: Prisma.CommunicationFindManyArgs
  ): Promise<PrismaCommunication[]> {
    return this.prisma.communication.findMany(args);
  }
  async communication(
    args: Prisma.CommunicationFindUniqueArgs
  ): Promise<PrismaCommunication | null> {
    return this.prisma.communication.findUnique(args);
  }
  async createCommunication(
    args: Prisma.CommunicationCreateArgs
  ): Promise<PrismaCommunication> {
    return this.prisma.communication.create(args);
  }
  async updateCommunication(
    args: Prisma.CommunicationUpdateArgs
  ): Promise<PrismaCommunication> {
    return this.prisma.communication.update(args);
  }
  async deleteCommunication(
    args: Prisma.CommunicationDeleteArgs
  ): Promise<PrismaCommunication> {
    return this.prisma.communication.delete(args);
  }
}
