/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { EnumLeadLeadSource } from "./EnumLeadLeadSource";
import { EnumLeadLeadStatus } from "./EnumLeadLeadStatus";
import { EnumLeadSource } from "./EnumLeadSource";
import { EnumLeadStatus } from "./EnumLeadStatus";

@InputType()
class LeadWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  contactInfo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  leadContactInfo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  leadFullName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  leadName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumLeadLeadSource,
  })
  @IsEnum(EnumLeadLeadSource)
  @IsOptional()
  @Field(() => EnumLeadLeadSource, {
    nullable: true,
  })
  leadSource?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumLeadLeadStatus,
  })
  @IsEnum(EnumLeadLeadStatus)
  @IsOptional()
  @Field(() => EnumLeadLeadStatus, {
    nullable: true,
  })
  leadStatus?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumLeadSource,
  })
  @IsEnum(EnumLeadSource)
  @IsOptional()
  @Field(() => EnumLeadSource, {
    nullable: true,
  })
  source?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumLeadStatus,
  })
  @IsEnum(EnumLeadStatus)
  @IsOptional()
  @Field(() => EnumLeadStatus, {
    nullable: true,
  })
  status?: "Option1";
}

export { LeadWhereInput as LeadWhereInput };
