/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, MaxLength, IsOptional, IsEnum } from "class-validator";
import { EnumLeadLeadSource } from "./EnumLeadLeadSource";
import { EnumLeadLeadStatus } from "./EnumLeadLeadStatus";
import { EnumLeadSource } from "./EnumLeadSource";
import { EnumLeadStatus } from "./EnumLeadStatus";

@InputType()
class LeadCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactInfo?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  leadContactInfo?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  leadFullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  leadName?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumLeadLeadSource,
  })
  @IsEnum(EnumLeadLeadSource)
  @IsOptional()
  @Field(() => EnumLeadLeadSource, {
    nullable: true,
  })
  leadSource?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumLeadLeadStatus,
  })
  @IsEnum(EnumLeadLeadStatus)
  @IsOptional()
  @Field(() => EnumLeadLeadStatus, {
    nullable: true,
  })
  leadStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumLeadSource,
  })
  @IsEnum(EnumLeadSource)
  @IsOptional()
  @Field(() => EnumLeadSource, {
    nullable: true,
  })
  source?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumLeadStatus,
  })
  @IsEnum(EnumLeadStatus)
  @IsOptional()
  @Field(() => EnumLeadStatus, {
    nullable: true,
  })
  status?: "Option1" | null;
}

export { LeadCreateInput as LeadCreateInput };
